name: Build and deploy Node.js app to Azure Web App - mr-photography-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: mr-photography-app
  LOCAL_APP_DIR: mr-photo-app
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies and build
        run: |
          cd ${{ env.LOCAL_APP_DIR }}
          npm ci
          npm run build
          
      - name: Verify and copy build
        run: |
          cd ${{ env.LOCAL_APP_DIR }}
          echo "=== Build verification ==="
          ls -la
          echo "=== .next directory ==="
          ls -la .next/ || echo "ERROR: .next directory not found!"
          
          echo "=== Creating deployment package ==="
          # Copy everything needed for deployment
          cp -r . ../deploy
          cd ../deploy
          
          echo "=== Deployment package contents ==="
          ls -la
          echo "=== .next in deployment ==="
          ls -la .next/ || echo "ERROR: .next missing in deployment!"
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Verify deployment package
        run: |
          echo "=== Deployment verification ==="
          ls -la
          echo "=== Checking .next ==="
          ls -la .next/ || echo "ERROR: .next directory missing!"
          echo "=== Checking server.js ==="
          ls -la server.js || echo "WARNING: server.js missing!"

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_MRPHOTOAPP }}