name: Build and deploy Node.js app to Azure Web App - mr-photography-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: mr-photography-app
  LOCAL_APP_DIR: mr-photo-app
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies and build
        run: |
          cd ${{ env.LOCAL_APP_DIR }}
          npm ci
          npm run build
          
      - name: Verify build output
        run: |
          cd ${{ env.LOCAL_APP_DIR }}
          echo "Checking build output..."
          ls -la .next/ || echo ".next directory not found"
          ls -la .next/standalone/ || echo ".next/standalone directory not found"
          
      - name: Prepare deployment package
        run: |
          cd ${{ env.LOCAL_APP_DIR }}
          # Create deployment directory
          mkdir -p deploy
          
          # Copy all necessary files
          cp package.json deploy/
          cp package-lock.json deploy/
          cp next.config.js deploy/ || true
          cp server.js deploy/ || true
          
          # Copy the entire .next directory (both standalone and regular)
          if [ -d ".next/standalone" ]; then
            echo "Using standalone build"
            cp -r .next/standalone/* deploy/
            cp -r .next/static deploy/.next/static
          else
            echo "Using regular build"
            cp -r .next deploy/
            cp -r node_modules deploy/
          fi
          
          # Copy public directory
          cp -r public deploy/ || true
          
          # Copy prisma if exists
          cp -r prisma deploy/ || true
          
          echo "Deployment package contents:"
          ls -la deploy/
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./${{ env.LOCAL_APP_DIR }}/deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Verify deployment package
        run: |
          echo "Deployment package contents:"
          ls -la
          ls -la .next/ || echo ".next directory not found in deployment"

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_MRPHOTOAPP }}